baseURL = 'https://syohex.github.io/'
copyright = "&copy; 2021. All rights reserved."
hasCJKLanguage = true
languageCode = 'en-us'
paginate = 10
theme = "tale"
title = 'Shohei Yoshida Diary'

[indexes]
tag = "tags"
topic = "topics"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fa fa-home fa-fw'></i>"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class='fa fa-info-circle fa-fw'></i>"
url = "/about/"
weight = 2

[social]
github = "syohex"
twitter = "syohex"
